### ISSUE TITLE
Using the main version of arrow2

### ISSUE THREAD

**Issue by blackrez** [jorgecarleitao/arrowdantic#11]
Hello,

I tried to use the latest of arrow2 but my build failed.

https://github.com/blackrez/arrowdantic/actions/runs/3563855994/jobs/5987131244

I think this is due to an odbc function.

But the odbc_fix patch is not merged with the master, what is the blocking point and how I can help ?

Thanks in advance (I'm starting to use it in production and it works great).

**Comment by jorgecarleitao** [comment]
Hey! Thanks a lot. Yes, unfortunately, the crate odbc has a limitation that requires us to use a fork of it to allow the design of this crate. That branch uses that fix, but because that fix is not in crates, we can't merge that branch to arrow2's main.

I just rebased that branch against latest main so we benefit from latest changes. Could you try again?

**Comment by blackrez** [comment]
Fixed with https://github.com/jorgecarleitao/arrowdantic/pull/12
